import type { CardDraft } from "./types";

/** Representative in-season soccer lift — shorter than extra hypertrophy days. */
export const sampleInSeasonSoccer: CardDraft = {
  hugoGroup: "soccer",
  weekNumber: 3,
  dayName: "Wednesday",
  sessionDate: "2026-09-16",
  focus: "Lower + power",
  title: "Week 3 — Wednesday — Soccer in-season (sample)",
  movements: [
    {
      label: "W",
      name: "Warmup Circuit",
      block: "Warmup",
      setCount: 0,
      targets: [],
      notes: "Spring ankle · hip hike · lunge ISO · pogos",
      fromPair: false,
      exerciseHtml: null,
    },
    {
      label: "1",
      name: "CMJ (Vertical Jump)",
      block: "Primer",
      setCount: 3,
      targets: ["Max Attempt", "Max Attempt", "Max Attempt"],
      notes: "Explosive · log best (in)",
      fromPair: false,
      exerciseHtml: null,
    },
    {
      label: "2",
      name: "Trap-Bar Deadlift",
      block: "Main",
      setCount: 4,
      targets: ["3 @ RPE 7", "3 @ RPE 8", "3 @ RPE 8", "3 @ RPE 8"],
      notes: "Stop short of grinders · in-season",
      fromPair: false,
      exerciseHtml: null,
    },
    {
      label: "3A",
      name: "DB Reverse Lunge",
      block: "Secondary",
      setCount: 3,
      targets: ["6/side @ RPE 7", "6/side @ RPE 8", "6/side @ RPE 8"],
      notes: "Trunk stacked",
      fromPair: true,
      exerciseHtml: null,
    },
    {
      label: "3B",
      name: "Copenhagen Side-Plank",
      block: "Secondary",
      setCount: 3,
      targets: ["20s/side", "20s/side", "20s/side"],
      notes: "Quality over time",
      fromPair: true,
      exerciseHtml: null,
    },
    {
      label: "4",
      name: "Nordic / Slider Leg Curl",
      block: "Accessory",
      setCount: 3,
      targets: ["5–6", "5–6", "5–6"],
      notes: "Eccentric control",
      fromPair: false,
      exerciseHtml: null,
    },
    {
      label: "5",
      name: "Med-Ball Rotation Throw",
      block: "Accessory",
      setCount: 2,
      targets: ["4/side", "4/side"],
      notes: "Submax · hip-shoulder timing",
      fromPair: false,
      exerciseHtml: null,
    },
  ],
};
